// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: cm/messages/message_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace TEKSteamClient.CM.Messages {

  /// <summary>Holder for reflection information generated from cm/messages/message_type.proto</summary>
  internal static partial class MessageTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for cm/messages/message_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessageTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5jbS9tZXNzYWdlcy9tZXNzYWdlX3R5cGUucHJvdG8SGnRla3N0ZWFtY2xp",
            "ZW50LmNtLm1lc3NhZ2VzKoUDCgtNZXNzYWdlVHlwZRILCgdJTlZBTElEEAAS",
            "CQoFTVVMVEkQARIcChdTRVJWSUNFX01FVEhPRF9SRVNQT05TRRCTARITCg5T",
            "RVJWSUNFX01FVEhPRBCXARIOCglIRUFSVEJFQVQQvwUSDAoHTE9HX09GRhDC",
            "BRIUCg9MT0dfT05fUkVTUE9OU0UQ7wUSGQoUREVQT1RfREVDUllQVElPTl9L",
            "RVkQvioSIgodREVQT1RfREVDUllQVElPTl9LRVlfUkVTUE9OU0UQvyoSFwoS",
            "U0VSVkVSX1VOQVZBSUxBQkxFEPwqEgsKBkxPR19PThCKKxIRCgxQUk9EVUNU",
            "X0lORk8Qx0USGgoVUFJPRFVDVF9JTkZPX1JFU1BPTlNFEMhFEhYKEVBJQ1Nf",
            "QUNDRVNTX1RPS0VOEMlFEh8KGlBJQ1NfQUNDRVNTX1RPS0VOX1JFU1BPTlNF",
            "EMpFEh4KGVNFUlZJQ0VfTUVUSE9EX05PVF9BVVRIRUQQzEwSCgoFSEVMTE8Q",
            "zUxCHaoCGlRFS1N0ZWFtQ2xpZW50LkNNLk1lc3NhZ2VzYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::TEKSteamClient.CM.Messages.MessageType), }, null, null));
    }
    #endregion

  }
  #region Enums
  internal enum MessageType {
    [pbr::OriginalName("INVALID")] Invalid = 0,
    [pbr::OriginalName("MULTI")] Multi = 1,
    [pbr::OriginalName("SERVICE_METHOD_RESPONSE")] ServiceMethodResponse = 147,
    [pbr::OriginalName("SERVICE_METHOD")] ServiceMethod = 151,
    [pbr::OriginalName("HEARTBEAT")] Heartbeat = 703,
    [pbr::OriginalName("LOG_OFF")] LogOff = 706,
    [pbr::OriginalName("LOG_ON_RESPONSE")] LogOnResponse = 751,
    [pbr::OriginalName("DEPOT_DECRYPTION_KEY")] DepotDecryptionKey = 5438,
    [pbr::OriginalName("DEPOT_DECRYPTION_KEY_RESPONSE")] DepotDecryptionKeyResponse = 5439,
    [pbr::OriginalName("SERVER_UNAVAILABLE")] ServerUnavailable = 5500,
    [pbr::OriginalName("LOG_ON")] LogOn = 5514,
    [pbr::OriginalName("PRODUCT_INFO")] ProductInfo = 8903,
    [pbr::OriginalName("PRODUCT_INFO_RESPONSE")] ProductInfoResponse = 8904,
    [pbr::OriginalName("PICS_ACCESS_TOKEN")] PicsAccessToken = 8905,
    [pbr::OriginalName("PICS_ACCESS_TOKEN_RESPONSE")] PicsAccessTokenResponse = 8906,
    [pbr::OriginalName("SERVICE_METHOD_NOT_AUTHED")] ServiceMethodNotAuthed = 9804,
    [pbr::OriginalName("HELLO")] Hello = 9805,
  }

  #endregion

}

#endregion Designer generated code
