// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: manifest/metadata.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace TEKSteamClient.Manifest {

  /// <summary>Holder for reflection information generated from manifest/metadata.proto</summary>
  internal static partial class MetadataReflection {

    #region Descriptor
    /// <summary>File descriptor for manifest/metadata.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MetadataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdtYW5pZmVzdC9tZXRhZGF0YS5wcm90bxIXdGVrc3RlYW1jbGllbnQubWFu",
            "aWZlc3QiZwoITWV0YWRhdGESCgoCaWQYAiABKAQSGwoTZmlsZW5hbWVzX2Vu",
            "Y3J5cHRlZBgEIAEoCBIZChF1bmNvbXByZXNzZWRfc2l6ZRgFIAEoBBIXCg9j",
            "b21wcmVzc2VkX3NpemUYBiABKARCGqoCF1RFS1N0ZWFtQ2xpZW50Lk1hbmlm",
            "ZXN0YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::TEKSteamClient.Manifest.Metadata), global::TEKSteamClient.Manifest.Metadata.Parser, new[]{ "Id", "FilenamesEncrypted", "UncompressedSize", "CompressedSize" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  internal sealed partial class Metadata : pb::IMessage<Metadata>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Metadata> _parser = new pb::MessageParser<Metadata>(() => new Metadata());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Metadata> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TEKSteamClient.Manifest.MetadataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Metadata() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Metadata(Metadata other) : this() {
      id_ = other.id_;
      filenamesEncrypted_ = other.filenamesEncrypted_;
      uncompressedSize_ = other.uncompressedSize_;
      compressedSize_ = other.compressedSize_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Metadata Clone() {
      return new Metadata(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 2;
    private ulong id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "filenames_encrypted" field.</summary>
    public const int FilenamesEncryptedFieldNumber = 4;
    private bool filenamesEncrypted_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool FilenamesEncrypted {
      get { return filenamesEncrypted_; }
      set {
        filenamesEncrypted_ = value;
      }
    }

    /// <summary>Field number for the "uncompressed_size" field.</summary>
    public const int UncompressedSizeFieldNumber = 5;
    private ulong uncompressedSize_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong UncompressedSize {
      get { return uncompressedSize_; }
      set {
        uncompressedSize_ = value;
      }
    }

    /// <summary>Field number for the "compressed_size" field.</summary>
    public const int CompressedSizeFieldNumber = 6;
    private ulong compressedSize_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong CompressedSize {
      get { return compressedSize_; }
      set {
        compressedSize_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Metadata);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Metadata other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (FilenamesEncrypted != other.FilenamesEncrypted) return false;
      if (UncompressedSize != other.UncompressedSize) return false;
      if (CompressedSize != other.CompressedSize) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0UL) hash ^= Id.GetHashCode();
      if (FilenamesEncrypted != false) hash ^= FilenamesEncrypted.GetHashCode();
      if (UncompressedSize != 0UL) hash ^= UncompressedSize.GetHashCode();
      if (CompressedSize != 0UL) hash ^= CompressedSize.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(Id);
      }
      if (FilenamesEncrypted != false) {
        output.WriteRawTag(32);
        output.WriteBool(FilenamesEncrypted);
      }
      if (UncompressedSize != 0UL) {
        output.WriteRawTag(40);
        output.WriteUInt64(UncompressedSize);
      }
      if (CompressedSize != 0UL) {
        output.WriteRawTag(48);
        output.WriteUInt64(CompressedSize);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(Id);
      }
      if (FilenamesEncrypted != false) {
        output.WriteRawTag(32);
        output.WriteBool(FilenamesEncrypted);
      }
      if (UncompressedSize != 0UL) {
        output.WriteRawTag(40);
        output.WriteUInt64(UncompressedSize);
      }
      if (CompressedSize != 0UL) {
        output.WriteRawTag(48);
        output.WriteUInt64(CompressedSize);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Id);
      }
      if (FilenamesEncrypted != false) {
        size += 1 + 1;
      }
      if (UncompressedSize != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(UncompressedSize);
      }
      if (CompressedSize != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(CompressedSize);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Metadata other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0UL) {
        Id = other.Id;
      }
      if (other.FilenamesEncrypted != false) {
        FilenamesEncrypted = other.FilenamesEncrypted;
      }
      if (other.UncompressedSize != 0UL) {
        UncompressedSize = other.UncompressedSize;
      }
      if (other.CompressedSize != 0UL) {
        CompressedSize = other.CompressedSize;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 16: {
            Id = input.ReadUInt64();
            break;
          }
          case 32: {
            FilenamesEncrypted = input.ReadBool();
            break;
          }
          case 40: {
            UncompressedSize = input.ReadUInt64();
            break;
          }
          case 48: {
            CompressedSize = input.ReadUInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 16: {
            Id = input.ReadUInt64();
            break;
          }
          case 32: {
            FilenamesEncrypted = input.ReadBool();
            break;
          }
          case 40: {
            UncompressedSize = input.ReadUInt64();
            break;
          }
          case 48: {
            CompressedSize = input.ReadUInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
