// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: cm/messages/bodies/auth_session.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace TEKSteamClient.CM.Messages.Bodies {

  /// <summary>Holder for reflection information generated from cm/messages/bodies/auth_session.proto</summary>
  internal static partial class AuthSessionReflection {

    #region Descriptor
    /// <summary>File descriptor for cm/messages/bodies/auth_session.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AuthSessionReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiVjbS9tZXNzYWdlcy9ib2RpZXMvYXV0aF9zZXNzaW9uLnByb3RvEiF0ZWtz",
            "dGVhbWNsaWVudC5jbS5tZXNzYWdlcy5ib2RpZXMivQIKEEJlZ2luQXV0aFNl",
            "c3Npb24SFAoMYWNjb3VudF9uYW1lGAIgASgJEhoKEmVuY3J5cHRlZF9wYXNz",
            "d29yZBgDIAEoCRIcChRlbmNyeXB0aW9uX3RpbWVzdGFtcBgEIAEoBBITCgtw",
            "ZXJzaXN0ZW5jZRgHIAEoBRISCgp3ZWJzaXRlX2lkGAggASgJElkKDmRldmlj",
            "ZV9kZXRhaWxzGAkgASgLMkEudGVrc3RlYW1jbGllbnQuY20ubWVzc2FnZXMu",
            "Ym9kaWVzLkJlZ2luQXV0aFNlc3Npb24uRGV2aWNlRGV0YWlscxpVCg1EZXZp",
            "Y2VEZXRhaWxzEhwKFGRldmljZV9mcmllbmRseV9uYW1lGAEgASgJEhUKDXBs",
            "YXRmb3JtX3R5cGUYAiABKAUSDwoHb3NfdHlwZRgDIAEoBSKHAgoYQmVnaW5B",
            "dXRoU2Vzc2lvblJlc3BvbnNlEhEKCWNsaWVudF9pZBgBIAEoBBISCgpyZXF1",
            "ZXN0X2lkGAIgASgMEhAKCGludGVydmFsGAMgASgCEm4KFWFsbG93ZWRfY29u",
            "ZmlybWF0aW9ucxgEIAMoCzJPLnRla3N0ZWFtY2xpZW50LmNtLm1lc3NhZ2Vz",
            "LmJvZGllcy5CZWdpbkF1dGhTZXNzaW9uUmVzcG9uc2UuQWxsb3dlZENvbmZp",
            "cm1hdGlvbhIQCghzdGVhbV9pZBgFIAEoBBowChNBbGxvd2VkQ29uZmlybWF0",
            "aW9uEhkKEWNvbmZpcm1hdGlvbl90eXBlGAEgASgFIlcKD1N1Ym1pdEd1YXJk",
            "Q29kZRIRCgljbGllbnRfaWQYASABKAQSEAoIc3RlYW1faWQYAiABKAYSDAoE",
            "Y29kZRgDIAEoCRIRCgljb2RlX3R5cGUYBCABKAUiOAoPUG9sbEF1dGhTZXNz",
            "aW9uEhEKCWNsaWVudF9pZBgBIAEoBBISCgpyZXF1ZXN0X2lkGAIgASgMIqEB",
            "ChdQb2xsQXV0aFNlc3Npb25SZXNwb25zZRIaCg1uZXdfY2xpZW50X2lkGAEg",
            "ASgESACIAQESGgoNcmVmcmVzaF90b2tlbhgDIAEoCUgBiAEBEhkKDGFjY291",
            "bnRfbmFtZRgGIAEoCUgCiAEBQhAKDl9uZXdfY2xpZW50X2lkQhAKDl9yZWZy",
            "ZXNoX3Rva2VuQg8KDV9hY2NvdW50X25hbWVCJKoCIVRFS1N0ZWFtQ2xpZW50",
            "LkNNLk1lc3NhZ2VzLkJvZGllc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::TEKSteamClient.CM.Messages.Bodies.BeginAuthSession), global::TEKSteamClient.CM.Messages.Bodies.BeginAuthSession.Parser, new[]{ "AccountName", "EncryptedPassword", "EncryptionTimestamp", "Persistence", "WebsiteId", "DeviceDetails" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::TEKSteamClient.CM.Messages.Bodies.BeginAuthSession.Types.DeviceDetails), global::TEKSteamClient.CM.Messages.Bodies.BeginAuthSession.Types.DeviceDetails.Parser, new[]{ "DeviceFriendlyName", "PlatformType", "OsType" }, null, null, null, null)}),
            new pbr::GeneratedClrTypeInfo(typeof(global::TEKSteamClient.CM.Messages.Bodies.BeginAuthSessionResponse), global::TEKSteamClient.CM.Messages.Bodies.BeginAuthSessionResponse.Parser, new[]{ "ClientId", "RequestId", "Interval", "AllowedConfirmations", "SteamId" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::TEKSteamClient.CM.Messages.Bodies.BeginAuthSessionResponse.Types.AllowedConfirmation), global::TEKSteamClient.CM.Messages.Bodies.BeginAuthSessionResponse.Types.AllowedConfirmation.Parser, new[]{ "ConfirmationType" }, null, null, null, null)}),
            new pbr::GeneratedClrTypeInfo(typeof(global::TEKSteamClient.CM.Messages.Bodies.SubmitGuardCode), global::TEKSteamClient.CM.Messages.Bodies.SubmitGuardCode.Parser, new[]{ "ClientId", "SteamId", "Code", "CodeType" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::TEKSteamClient.CM.Messages.Bodies.PollAuthSession), global::TEKSteamClient.CM.Messages.Bodies.PollAuthSession.Parser, new[]{ "ClientId", "RequestId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::TEKSteamClient.CM.Messages.Bodies.PollAuthSessionResponse), global::TEKSteamClient.CM.Messages.Bodies.PollAuthSessionResponse.Parser, new[]{ "NewClientId", "RefreshToken", "AccountName" }, new[]{ "NewClientId", "RefreshToken", "AccountName" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  internal sealed partial class BeginAuthSession : pb::IMessage<BeginAuthSession>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BeginAuthSession> _parser = new pb::MessageParser<BeginAuthSession>(() => new BeginAuthSession());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BeginAuthSession> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TEKSteamClient.CM.Messages.Bodies.AuthSessionReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BeginAuthSession() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BeginAuthSession(BeginAuthSession other) : this() {
      accountName_ = other.accountName_;
      encryptedPassword_ = other.encryptedPassword_;
      encryptionTimestamp_ = other.encryptionTimestamp_;
      persistence_ = other.persistence_;
      websiteId_ = other.websiteId_;
      deviceDetails_ = other.deviceDetails_ != null ? other.deviceDetails_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BeginAuthSession Clone() {
      return new BeginAuthSession(this);
    }

    /// <summary>Field number for the "account_name" field.</summary>
    public const int AccountNameFieldNumber = 2;
    private string accountName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AccountName {
      get { return accountName_; }
      set {
        accountName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "encrypted_password" field.</summary>
    public const int EncryptedPasswordFieldNumber = 3;
    private string encryptedPassword_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string EncryptedPassword {
      get { return encryptedPassword_; }
      set {
        encryptedPassword_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "encryption_timestamp" field.</summary>
    public const int EncryptionTimestampFieldNumber = 4;
    private ulong encryptionTimestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong EncryptionTimestamp {
      get { return encryptionTimestamp_; }
      set {
        encryptionTimestamp_ = value;
      }
    }

    /// <summary>Field number for the "persistence" field.</summary>
    public const int PersistenceFieldNumber = 7;
    private int persistence_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Persistence {
      get { return persistence_; }
      set {
        persistence_ = value;
      }
    }

    /// <summary>Field number for the "website_id" field.</summary>
    public const int WebsiteIdFieldNumber = 8;
    private string websiteId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string WebsiteId {
      get { return websiteId_; }
      set {
        websiteId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "device_details" field.</summary>
    public const int DeviceDetailsFieldNumber = 9;
    private global::TEKSteamClient.CM.Messages.Bodies.BeginAuthSession.Types.DeviceDetails deviceDetails_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::TEKSteamClient.CM.Messages.Bodies.BeginAuthSession.Types.DeviceDetails DeviceDetails {
      get { return deviceDetails_; }
      set {
        deviceDetails_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BeginAuthSession);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BeginAuthSession other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AccountName != other.AccountName) return false;
      if (EncryptedPassword != other.EncryptedPassword) return false;
      if (EncryptionTimestamp != other.EncryptionTimestamp) return false;
      if (Persistence != other.Persistence) return false;
      if (WebsiteId != other.WebsiteId) return false;
      if (!object.Equals(DeviceDetails, other.DeviceDetails)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (AccountName.Length != 0) hash ^= AccountName.GetHashCode();
      if (EncryptedPassword.Length != 0) hash ^= EncryptedPassword.GetHashCode();
      if (EncryptionTimestamp != 0UL) hash ^= EncryptionTimestamp.GetHashCode();
      if (Persistence != 0) hash ^= Persistence.GetHashCode();
      if (WebsiteId.Length != 0) hash ^= WebsiteId.GetHashCode();
      if (deviceDetails_ != null) hash ^= DeviceDetails.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (AccountName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(AccountName);
      }
      if (EncryptedPassword.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(EncryptedPassword);
      }
      if (EncryptionTimestamp != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(EncryptionTimestamp);
      }
      if (Persistence != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(Persistence);
      }
      if (WebsiteId.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(WebsiteId);
      }
      if (deviceDetails_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(DeviceDetails);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (AccountName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(AccountName);
      }
      if (EncryptedPassword.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(EncryptedPassword);
      }
      if (EncryptionTimestamp != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(EncryptionTimestamp);
      }
      if (Persistence != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(Persistence);
      }
      if (WebsiteId.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(WebsiteId);
      }
      if (deviceDetails_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(DeviceDetails);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (AccountName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AccountName);
      }
      if (EncryptedPassword.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EncryptedPassword);
      }
      if (EncryptionTimestamp != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(EncryptionTimestamp);
      }
      if (Persistence != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Persistence);
      }
      if (WebsiteId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(WebsiteId);
      }
      if (deviceDetails_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DeviceDetails);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BeginAuthSession other) {
      if (other == null) {
        return;
      }
      if (other.AccountName.Length != 0) {
        AccountName = other.AccountName;
      }
      if (other.EncryptedPassword.Length != 0) {
        EncryptedPassword = other.EncryptedPassword;
      }
      if (other.EncryptionTimestamp != 0UL) {
        EncryptionTimestamp = other.EncryptionTimestamp;
      }
      if (other.Persistence != 0) {
        Persistence = other.Persistence;
      }
      if (other.WebsiteId.Length != 0) {
        WebsiteId = other.WebsiteId;
      }
      if (other.deviceDetails_ != null) {
        if (deviceDetails_ == null) {
          DeviceDetails = new global::TEKSteamClient.CM.Messages.Bodies.BeginAuthSession.Types.DeviceDetails();
        }
        DeviceDetails.MergeFrom(other.DeviceDetails);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 18: {
            AccountName = input.ReadString();
            break;
          }
          case 26: {
            EncryptedPassword = input.ReadString();
            break;
          }
          case 32: {
            EncryptionTimestamp = input.ReadUInt64();
            break;
          }
          case 56: {
            Persistence = input.ReadInt32();
            break;
          }
          case 66: {
            WebsiteId = input.ReadString();
            break;
          }
          case 74: {
            if (deviceDetails_ == null) {
              DeviceDetails = new global::TEKSteamClient.CM.Messages.Bodies.BeginAuthSession.Types.DeviceDetails();
            }
            input.ReadMessage(DeviceDetails);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 18: {
            AccountName = input.ReadString();
            break;
          }
          case 26: {
            EncryptedPassword = input.ReadString();
            break;
          }
          case 32: {
            EncryptionTimestamp = input.ReadUInt64();
            break;
          }
          case 56: {
            Persistence = input.ReadInt32();
            break;
          }
          case 66: {
            WebsiteId = input.ReadString();
            break;
          }
          case 74: {
            if (deviceDetails_ == null) {
              DeviceDetails = new global::TEKSteamClient.CM.Messages.Bodies.BeginAuthSession.Types.DeviceDetails();
            }
            input.ReadMessage(DeviceDetails);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the BeginAuthSession message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      internal sealed partial class DeviceDetails : pb::IMessage<DeviceDetails>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<DeviceDetails> _parser = new pb::MessageParser<DeviceDetails>(() => new DeviceDetails());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<DeviceDetails> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::TEKSteamClient.CM.Messages.Bodies.BeginAuthSession.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public DeviceDetails() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public DeviceDetails(DeviceDetails other) : this() {
          deviceFriendlyName_ = other.deviceFriendlyName_;
          platformType_ = other.platformType_;
          osType_ = other.osType_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public DeviceDetails Clone() {
          return new DeviceDetails(this);
        }

        /// <summary>Field number for the "device_friendly_name" field.</summary>
        public const int DeviceFriendlyNameFieldNumber = 1;
        private string deviceFriendlyName_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string DeviceFriendlyName {
          get { return deviceFriendlyName_; }
          set {
            deviceFriendlyName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "platform_type" field.</summary>
        public const int PlatformTypeFieldNumber = 2;
        private int platformType_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int PlatformType {
          get { return platformType_; }
          set {
            platformType_ = value;
          }
        }

        /// <summary>Field number for the "os_type" field.</summary>
        public const int OsTypeFieldNumber = 3;
        private int osType_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int OsType {
          get { return osType_; }
          set {
            osType_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as DeviceDetails);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(DeviceDetails other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (DeviceFriendlyName != other.DeviceFriendlyName) return false;
          if (PlatformType != other.PlatformType) return false;
          if (OsType != other.OsType) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (DeviceFriendlyName.Length != 0) hash ^= DeviceFriendlyName.GetHashCode();
          if (PlatformType != 0) hash ^= PlatformType.GetHashCode();
          if (OsType != 0) hash ^= OsType.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (DeviceFriendlyName.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(DeviceFriendlyName);
          }
          if (PlatformType != 0) {
            output.WriteRawTag(16);
            output.WriteInt32(PlatformType);
          }
          if (OsType != 0) {
            output.WriteRawTag(24);
            output.WriteInt32(OsType);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (DeviceFriendlyName.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(DeviceFriendlyName);
          }
          if (PlatformType != 0) {
            output.WriteRawTag(16);
            output.WriteInt32(PlatformType);
          }
          if (OsType != 0) {
            output.WriteRawTag(24);
            output.WriteInt32(OsType);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (DeviceFriendlyName.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(DeviceFriendlyName);
          }
          if (PlatformType != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(PlatformType);
          }
          if (OsType != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(OsType);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(DeviceDetails other) {
          if (other == null) {
            return;
          }
          if (other.DeviceFriendlyName.Length != 0) {
            DeviceFriendlyName = other.DeviceFriendlyName;
          }
          if (other.PlatformType != 0) {
            PlatformType = other.PlatformType;
          }
          if (other.OsType != 0) {
            OsType = other.OsType;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                DeviceFriendlyName = input.ReadString();
                break;
              }
              case 16: {
                PlatformType = input.ReadInt32();
                break;
              }
              case 24: {
                OsType = input.ReadInt32();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                DeviceFriendlyName = input.ReadString();
                break;
              }
              case 16: {
                PlatformType = input.ReadInt32();
                break;
              }
              case 24: {
                OsType = input.ReadInt32();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  internal sealed partial class BeginAuthSessionResponse : pb::IMessage<BeginAuthSessionResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BeginAuthSessionResponse> _parser = new pb::MessageParser<BeginAuthSessionResponse>(() => new BeginAuthSessionResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BeginAuthSessionResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TEKSteamClient.CM.Messages.Bodies.AuthSessionReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BeginAuthSessionResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BeginAuthSessionResponse(BeginAuthSessionResponse other) : this() {
      clientId_ = other.clientId_;
      requestId_ = other.requestId_;
      interval_ = other.interval_;
      allowedConfirmations_ = other.allowedConfirmations_.Clone();
      steamId_ = other.steamId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BeginAuthSessionResponse Clone() {
      return new BeginAuthSessionResponse(this);
    }

    /// <summary>Field number for the "client_id" field.</summary>
    public const int ClientIdFieldNumber = 1;
    private ulong clientId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong ClientId {
      get { return clientId_; }
      set {
        clientId_ = value;
      }
    }

    /// <summary>Field number for the "request_id" field.</summary>
    public const int RequestIdFieldNumber = 2;
    private pb::ByteString requestId_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString RequestId {
      get { return requestId_; }
      set {
        requestId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "interval" field.</summary>
    public const int IntervalFieldNumber = 3;
    private float interval_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Interval {
      get { return interval_; }
      set {
        interval_ = value;
      }
    }

    /// <summary>Field number for the "allowed_confirmations" field.</summary>
    public const int AllowedConfirmationsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::TEKSteamClient.CM.Messages.Bodies.BeginAuthSessionResponse.Types.AllowedConfirmation> _repeated_allowedConfirmations_codec
        = pb::FieldCodec.ForMessage(34, global::TEKSteamClient.CM.Messages.Bodies.BeginAuthSessionResponse.Types.AllowedConfirmation.Parser);
    private readonly pbc::RepeatedField<global::TEKSteamClient.CM.Messages.Bodies.BeginAuthSessionResponse.Types.AllowedConfirmation> allowedConfirmations_ = new pbc::RepeatedField<global::TEKSteamClient.CM.Messages.Bodies.BeginAuthSessionResponse.Types.AllowedConfirmation>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::TEKSteamClient.CM.Messages.Bodies.BeginAuthSessionResponse.Types.AllowedConfirmation> AllowedConfirmations {
      get { return allowedConfirmations_; }
    }

    /// <summary>Field number for the "steam_id" field.</summary>
    public const int SteamIdFieldNumber = 5;
    private ulong steamId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong SteamId {
      get { return steamId_; }
      set {
        steamId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BeginAuthSessionResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BeginAuthSessionResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ClientId != other.ClientId) return false;
      if (RequestId != other.RequestId) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Interval, other.Interval)) return false;
      if(!allowedConfirmations_.Equals(other.allowedConfirmations_)) return false;
      if (SteamId != other.SteamId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ClientId != 0UL) hash ^= ClientId.GetHashCode();
      if (RequestId.Length != 0) hash ^= RequestId.GetHashCode();
      if (Interval != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Interval);
      hash ^= allowedConfirmations_.GetHashCode();
      if (SteamId != 0UL) hash ^= SteamId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ClientId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(ClientId);
      }
      if (RequestId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(RequestId);
      }
      if (Interval != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Interval);
      }
      allowedConfirmations_.WriteTo(output, _repeated_allowedConfirmations_codec);
      if (SteamId != 0UL) {
        output.WriteRawTag(40);
        output.WriteUInt64(SteamId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ClientId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(ClientId);
      }
      if (RequestId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(RequestId);
      }
      if (Interval != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Interval);
      }
      allowedConfirmations_.WriteTo(ref output, _repeated_allowedConfirmations_codec);
      if (SteamId != 0UL) {
        output.WriteRawTag(40);
        output.WriteUInt64(SteamId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ClientId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ClientId);
      }
      if (RequestId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(RequestId);
      }
      if (Interval != 0F) {
        size += 1 + 4;
      }
      size += allowedConfirmations_.CalculateSize(_repeated_allowedConfirmations_codec);
      if (SteamId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(SteamId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BeginAuthSessionResponse other) {
      if (other == null) {
        return;
      }
      if (other.ClientId != 0UL) {
        ClientId = other.ClientId;
      }
      if (other.RequestId.Length != 0) {
        RequestId = other.RequestId;
      }
      if (other.Interval != 0F) {
        Interval = other.Interval;
      }
      allowedConfirmations_.Add(other.allowedConfirmations_);
      if (other.SteamId != 0UL) {
        SteamId = other.SteamId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ClientId = input.ReadUInt64();
            break;
          }
          case 18: {
            RequestId = input.ReadBytes();
            break;
          }
          case 29: {
            Interval = input.ReadFloat();
            break;
          }
          case 34: {
            allowedConfirmations_.AddEntriesFrom(input, _repeated_allowedConfirmations_codec);
            break;
          }
          case 40: {
            SteamId = input.ReadUInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ClientId = input.ReadUInt64();
            break;
          }
          case 18: {
            RequestId = input.ReadBytes();
            break;
          }
          case 29: {
            Interval = input.ReadFloat();
            break;
          }
          case 34: {
            allowedConfirmations_.AddEntriesFrom(ref input, _repeated_allowedConfirmations_codec);
            break;
          }
          case 40: {
            SteamId = input.ReadUInt64();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the BeginAuthSessionResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      internal sealed partial class AllowedConfirmation : pb::IMessage<AllowedConfirmation>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<AllowedConfirmation> _parser = new pb::MessageParser<AllowedConfirmation>(() => new AllowedConfirmation());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<AllowedConfirmation> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::TEKSteamClient.CM.Messages.Bodies.BeginAuthSessionResponse.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public AllowedConfirmation() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public AllowedConfirmation(AllowedConfirmation other) : this() {
          confirmationType_ = other.confirmationType_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public AllowedConfirmation Clone() {
          return new AllowedConfirmation(this);
        }

        /// <summary>Field number for the "confirmation_type" field.</summary>
        public const int ConfirmationTypeFieldNumber = 1;
        private int confirmationType_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int ConfirmationType {
          get { return confirmationType_; }
          set {
            confirmationType_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as AllowedConfirmation);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(AllowedConfirmation other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (ConfirmationType != other.ConfirmationType) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (ConfirmationType != 0) hash ^= ConfirmationType.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (ConfirmationType != 0) {
            output.WriteRawTag(8);
            output.WriteInt32(ConfirmationType);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (ConfirmationType != 0) {
            output.WriteRawTag(8);
            output.WriteInt32(ConfirmationType);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (ConfirmationType != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(ConfirmationType);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(AllowedConfirmation other) {
          if (other == null) {
            return;
          }
          if (other.ConfirmationType != 0) {
            ConfirmationType = other.ConfirmationType;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                ConfirmationType = input.ReadInt32();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                ConfirmationType = input.ReadInt32();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  internal sealed partial class SubmitGuardCode : pb::IMessage<SubmitGuardCode>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SubmitGuardCode> _parser = new pb::MessageParser<SubmitGuardCode>(() => new SubmitGuardCode());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SubmitGuardCode> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TEKSteamClient.CM.Messages.Bodies.AuthSessionReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SubmitGuardCode() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SubmitGuardCode(SubmitGuardCode other) : this() {
      clientId_ = other.clientId_;
      steamId_ = other.steamId_;
      code_ = other.code_;
      codeType_ = other.codeType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SubmitGuardCode Clone() {
      return new SubmitGuardCode(this);
    }

    /// <summary>Field number for the "client_id" field.</summary>
    public const int ClientIdFieldNumber = 1;
    private ulong clientId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong ClientId {
      get { return clientId_; }
      set {
        clientId_ = value;
      }
    }

    /// <summary>Field number for the "steam_id" field.</summary>
    public const int SteamIdFieldNumber = 2;
    private ulong steamId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong SteamId {
      get { return steamId_; }
      set {
        steamId_ = value;
      }
    }

    /// <summary>Field number for the "code" field.</summary>
    public const int CodeFieldNumber = 3;
    private string code_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Code {
      get { return code_; }
      set {
        code_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "code_type" field.</summary>
    public const int CodeTypeFieldNumber = 4;
    private int codeType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CodeType {
      get { return codeType_; }
      set {
        codeType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SubmitGuardCode);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SubmitGuardCode other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ClientId != other.ClientId) return false;
      if (SteamId != other.SteamId) return false;
      if (Code != other.Code) return false;
      if (CodeType != other.CodeType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ClientId != 0UL) hash ^= ClientId.GetHashCode();
      if (SteamId != 0UL) hash ^= SteamId.GetHashCode();
      if (Code.Length != 0) hash ^= Code.GetHashCode();
      if (CodeType != 0) hash ^= CodeType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ClientId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(ClientId);
      }
      if (SteamId != 0UL) {
        output.WriteRawTag(17);
        output.WriteFixed64(SteamId);
      }
      if (Code.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Code);
      }
      if (CodeType != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(CodeType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ClientId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(ClientId);
      }
      if (SteamId != 0UL) {
        output.WriteRawTag(17);
        output.WriteFixed64(SteamId);
      }
      if (Code.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Code);
      }
      if (CodeType != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(CodeType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ClientId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ClientId);
      }
      if (SteamId != 0UL) {
        size += 1 + 8;
      }
      if (Code.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Code);
      }
      if (CodeType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CodeType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SubmitGuardCode other) {
      if (other == null) {
        return;
      }
      if (other.ClientId != 0UL) {
        ClientId = other.ClientId;
      }
      if (other.SteamId != 0UL) {
        SteamId = other.SteamId;
      }
      if (other.Code.Length != 0) {
        Code = other.Code;
      }
      if (other.CodeType != 0) {
        CodeType = other.CodeType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ClientId = input.ReadUInt64();
            break;
          }
          case 17: {
            SteamId = input.ReadFixed64();
            break;
          }
          case 26: {
            Code = input.ReadString();
            break;
          }
          case 32: {
            CodeType = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ClientId = input.ReadUInt64();
            break;
          }
          case 17: {
            SteamId = input.ReadFixed64();
            break;
          }
          case 26: {
            Code = input.ReadString();
            break;
          }
          case 32: {
            CodeType = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  internal sealed partial class PollAuthSession : pb::IMessage<PollAuthSession>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PollAuthSession> _parser = new pb::MessageParser<PollAuthSession>(() => new PollAuthSession());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PollAuthSession> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TEKSteamClient.CM.Messages.Bodies.AuthSessionReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PollAuthSession() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PollAuthSession(PollAuthSession other) : this() {
      clientId_ = other.clientId_;
      requestId_ = other.requestId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PollAuthSession Clone() {
      return new PollAuthSession(this);
    }

    /// <summary>Field number for the "client_id" field.</summary>
    public const int ClientIdFieldNumber = 1;
    private ulong clientId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong ClientId {
      get { return clientId_; }
      set {
        clientId_ = value;
      }
    }

    /// <summary>Field number for the "request_id" field.</summary>
    public const int RequestIdFieldNumber = 2;
    private pb::ByteString requestId_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString RequestId {
      get { return requestId_; }
      set {
        requestId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PollAuthSession);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PollAuthSession other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ClientId != other.ClientId) return false;
      if (RequestId != other.RequestId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ClientId != 0UL) hash ^= ClientId.GetHashCode();
      if (RequestId.Length != 0) hash ^= RequestId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ClientId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(ClientId);
      }
      if (RequestId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(RequestId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ClientId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(ClientId);
      }
      if (RequestId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(RequestId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ClientId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ClientId);
      }
      if (RequestId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(RequestId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PollAuthSession other) {
      if (other == null) {
        return;
      }
      if (other.ClientId != 0UL) {
        ClientId = other.ClientId;
      }
      if (other.RequestId.Length != 0) {
        RequestId = other.RequestId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ClientId = input.ReadUInt64();
            break;
          }
          case 18: {
            RequestId = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ClientId = input.ReadUInt64();
            break;
          }
          case 18: {
            RequestId = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  internal sealed partial class PollAuthSessionResponse : pb::IMessage<PollAuthSessionResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PollAuthSessionResponse> _parser = new pb::MessageParser<PollAuthSessionResponse>(() => new PollAuthSessionResponse());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PollAuthSessionResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TEKSteamClient.CM.Messages.Bodies.AuthSessionReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PollAuthSessionResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PollAuthSessionResponse(PollAuthSessionResponse other) : this() {
      _hasBits0 = other._hasBits0;
      newClientId_ = other.newClientId_;
      refreshToken_ = other.refreshToken_;
      accountName_ = other.accountName_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PollAuthSessionResponse Clone() {
      return new PollAuthSessionResponse(this);
    }

    /// <summary>Field number for the "new_client_id" field.</summary>
    public const int NewClientIdFieldNumber = 1;
    private readonly static ulong NewClientIdDefaultValue = 0UL;

    private ulong newClientId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong NewClientId {
      get { if ((_hasBits0 & 1) != 0) { return newClientId_; } else { return NewClientIdDefaultValue; } }
      set {
        _hasBits0 |= 1;
        newClientId_ = value;
      }
    }
    /// <summary>Gets whether the "new_client_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasNewClientId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "new_client_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearNewClientId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "refresh_token" field.</summary>
    public const int RefreshTokenFieldNumber = 3;
    private readonly static string RefreshTokenDefaultValue = "";

    private string refreshToken_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RefreshToken {
      get { return refreshToken_ ?? RefreshTokenDefaultValue; }
      set {
        refreshToken_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "refresh_token" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasRefreshToken {
      get { return refreshToken_ != null; }
    }
    /// <summary>Clears the value of the "refresh_token" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearRefreshToken() {
      refreshToken_ = null;
    }

    /// <summary>Field number for the "account_name" field.</summary>
    public const int AccountNameFieldNumber = 6;
    private readonly static string AccountNameDefaultValue = "";

    private string accountName_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AccountName {
      get { return accountName_ ?? AccountNameDefaultValue; }
      set {
        accountName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "account_name" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAccountName {
      get { return accountName_ != null; }
    }
    /// <summary>Clears the value of the "account_name" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAccountName() {
      accountName_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PollAuthSessionResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PollAuthSessionResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (NewClientId != other.NewClientId) return false;
      if (RefreshToken != other.RefreshToken) return false;
      if (AccountName != other.AccountName) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasNewClientId) hash ^= NewClientId.GetHashCode();
      if (HasRefreshToken) hash ^= RefreshToken.GetHashCode();
      if (HasAccountName) hash ^= AccountName.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasNewClientId) {
        output.WriteRawTag(8);
        output.WriteUInt64(NewClientId);
      }
      if (HasRefreshToken) {
        output.WriteRawTag(26);
        output.WriteString(RefreshToken);
      }
      if (HasAccountName) {
        output.WriteRawTag(50);
        output.WriteString(AccountName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasNewClientId) {
        output.WriteRawTag(8);
        output.WriteUInt64(NewClientId);
      }
      if (HasRefreshToken) {
        output.WriteRawTag(26);
        output.WriteString(RefreshToken);
      }
      if (HasAccountName) {
        output.WriteRawTag(50);
        output.WriteString(AccountName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasNewClientId) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(NewClientId);
      }
      if (HasRefreshToken) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RefreshToken);
      }
      if (HasAccountName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AccountName);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PollAuthSessionResponse other) {
      if (other == null) {
        return;
      }
      if (other.HasNewClientId) {
        NewClientId = other.NewClientId;
      }
      if (other.HasRefreshToken) {
        RefreshToken = other.RefreshToken;
      }
      if (other.HasAccountName) {
        AccountName = other.AccountName;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            NewClientId = input.ReadUInt64();
            break;
          }
          case 26: {
            RefreshToken = input.ReadString();
            break;
          }
          case 50: {
            AccountName = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            NewClientId = input.ReadUInt64();
            break;
          }
          case 26: {
            RefreshToken = input.ReadString();
            break;
          }
          case 50: {
            AccountName = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
