// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: cm/messages/bodies/query_workshop_items.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace TEKSteamClient.CM.Messages.Bodies {

  /// <summary>Holder for reflection information generated from cm/messages/bodies/query_workshop_items.proto</summary>
  internal static partial class QueryWorkshopItemsReflection {

    #region Descriptor
    /// <summary>File descriptor for cm/messages/bodies/query_workshop_items.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static QueryWorkshopItemsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci1jbS9tZXNzYWdlcy9ib2RpZXMvcXVlcnlfd29ya3Nob3BfaXRlbXMucHJv",
            "dG8SIXRla3N0ZWFtY2xpZW50LmNtLm1lc3NhZ2VzLmJvZGllcyKNAQoSUXVl",
            "cnlXb3Jrc2hvcEl0ZW1zEgwKBHBhZ2UYAiABKA0SFgoOaXRlbXNfcGVyX3Bh",
            "Z2UYAyABKA0SDgoGYXBwX2lkGAUgASgNEhgKC3NlYXJjaF90ZXh0GAsgASgJ",
            "SACIAQESFwoPcmV0dXJuX21ldGFkYXRhGCAgASgIQg4KDF9zZWFyY2hfdGV4",
            "dCLbAgoaUXVlcnlXb3Jrc2hvcEl0ZW1zUmVzcG9uc2USDQoFdG90YWwYASAB",
            "KA0SUQoFaXRlbXMYAiADKAsyQi50ZWtzdGVhbWNsaWVudC5jbS5tZXNzYWdl",
            "cy5ib2RpZXMuUXVlcnlXb3Jrc2hvcEl0ZW1zUmVzcG9uc2UuSXRlbRraAQoE",
            "SXRlbRITCgZyZXN1bHQYASABKAVIAIgBARIPCgJpZBgCIAEoBEgBiAEBEhgK",
            "C3ByZXZpZXdfdXJsGAsgASgJSAKIAQESGAoLbWFuaWZlc3RfaWQYDiABKAZI",
            "A4gBARIRCgRuYW1lGBAgASgJSASIAQESGQoMbGFzdF91cGRhdGVkGBQgASgD",
            "SAWIAQFCCQoHX3Jlc3VsdEIFCgNfaWRCDgoMX3ByZXZpZXdfdXJsQg4KDF9t",
            "YW5pZmVzdF9pZEIHCgVfbmFtZUIPCg1fbGFzdF91cGRhdGVkQiSqAiFURUtT",
            "dGVhbUNsaWVudC5DTS5NZXNzYWdlcy5Cb2RpZXNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::TEKSteamClient.CM.Messages.Bodies.QueryWorkshopItems), global::TEKSteamClient.CM.Messages.Bodies.QueryWorkshopItems.Parser, new[]{ "Page", "ItemsPerPage", "AppId", "SearchText", "ReturnMetadata" }, new[]{ "SearchText" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::TEKSteamClient.CM.Messages.Bodies.QueryWorkshopItemsResponse), global::TEKSteamClient.CM.Messages.Bodies.QueryWorkshopItemsResponse.Parser, new[]{ "Total", "Items" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::TEKSteamClient.CM.Messages.Bodies.QueryWorkshopItemsResponse.Types.Item), global::TEKSteamClient.CM.Messages.Bodies.QueryWorkshopItemsResponse.Types.Item.Parser, new[]{ "Result", "Id", "PreviewUrl", "ManifestId", "Name", "LastUpdated" }, new[]{ "Result", "Id", "PreviewUrl", "ManifestId", "Name", "LastUpdated" }, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  internal sealed partial class QueryWorkshopItems : pb::IMessage<QueryWorkshopItems>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<QueryWorkshopItems> _parser = new pb::MessageParser<QueryWorkshopItems>(() => new QueryWorkshopItems());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<QueryWorkshopItems> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TEKSteamClient.CM.Messages.Bodies.QueryWorkshopItemsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QueryWorkshopItems() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QueryWorkshopItems(QueryWorkshopItems other) : this() {
      page_ = other.page_;
      itemsPerPage_ = other.itemsPerPage_;
      appId_ = other.appId_;
      searchText_ = other.searchText_;
      returnMetadata_ = other.returnMetadata_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QueryWorkshopItems Clone() {
      return new QueryWorkshopItems(this);
    }

    /// <summary>Field number for the "page" field.</summary>
    public const int PageFieldNumber = 2;
    private uint page_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Page {
      get { return page_; }
      set {
        page_ = value;
      }
    }

    /// <summary>Field number for the "items_per_page" field.</summary>
    public const int ItemsPerPageFieldNumber = 3;
    private uint itemsPerPage_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ItemsPerPage {
      get { return itemsPerPage_; }
      set {
        itemsPerPage_ = value;
      }
    }

    /// <summary>Field number for the "app_id" field.</summary>
    public const int AppIdFieldNumber = 5;
    private uint appId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint AppId {
      get { return appId_; }
      set {
        appId_ = value;
      }
    }

    /// <summary>Field number for the "search_text" field.</summary>
    public const int SearchTextFieldNumber = 11;
    private readonly static string SearchTextDefaultValue = "";

    private string searchText_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SearchText {
      get { return searchText_ ?? SearchTextDefaultValue; }
      set {
        searchText_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "search_text" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasSearchText {
      get { return searchText_ != null; }
    }
    /// <summary>Clears the value of the "search_text" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearSearchText() {
      searchText_ = null;
    }

    /// <summary>Field number for the "return_metadata" field.</summary>
    public const int ReturnMetadataFieldNumber = 32;
    private bool returnMetadata_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool ReturnMetadata {
      get { return returnMetadata_; }
      set {
        returnMetadata_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as QueryWorkshopItems);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(QueryWorkshopItems other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Page != other.Page) return false;
      if (ItemsPerPage != other.ItemsPerPage) return false;
      if (AppId != other.AppId) return false;
      if (SearchText != other.SearchText) return false;
      if (ReturnMetadata != other.ReturnMetadata) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Page != 0) hash ^= Page.GetHashCode();
      if (ItemsPerPage != 0) hash ^= ItemsPerPage.GetHashCode();
      if (AppId != 0) hash ^= AppId.GetHashCode();
      if (HasSearchText) hash ^= SearchText.GetHashCode();
      if (ReturnMetadata != false) hash ^= ReturnMetadata.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Page != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Page);
      }
      if (ItemsPerPage != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(ItemsPerPage);
      }
      if (AppId != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(AppId);
      }
      if (HasSearchText) {
        output.WriteRawTag(90);
        output.WriteString(SearchText);
      }
      if (ReturnMetadata != false) {
        output.WriteRawTag(128, 2);
        output.WriteBool(ReturnMetadata);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Page != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Page);
      }
      if (ItemsPerPage != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(ItemsPerPage);
      }
      if (AppId != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(AppId);
      }
      if (HasSearchText) {
        output.WriteRawTag(90);
        output.WriteString(SearchText);
      }
      if (ReturnMetadata != false) {
        output.WriteRawTag(128, 2);
        output.WriteBool(ReturnMetadata);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Page != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Page);
      }
      if (ItemsPerPage != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ItemsPerPage);
      }
      if (AppId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(AppId);
      }
      if (HasSearchText) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SearchText);
      }
      if (ReturnMetadata != false) {
        size += 2 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(QueryWorkshopItems other) {
      if (other == null) {
        return;
      }
      if (other.Page != 0) {
        Page = other.Page;
      }
      if (other.ItemsPerPage != 0) {
        ItemsPerPage = other.ItemsPerPage;
      }
      if (other.AppId != 0) {
        AppId = other.AppId;
      }
      if (other.HasSearchText) {
        SearchText = other.SearchText;
      }
      if (other.ReturnMetadata != false) {
        ReturnMetadata = other.ReturnMetadata;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 16: {
            Page = input.ReadUInt32();
            break;
          }
          case 24: {
            ItemsPerPage = input.ReadUInt32();
            break;
          }
          case 40: {
            AppId = input.ReadUInt32();
            break;
          }
          case 90: {
            SearchText = input.ReadString();
            break;
          }
          case 256: {
            ReturnMetadata = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 16: {
            Page = input.ReadUInt32();
            break;
          }
          case 24: {
            ItemsPerPage = input.ReadUInt32();
            break;
          }
          case 40: {
            AppId = input.ReadUInt32();
            break;
          }
          case 90: {
            SearchText = input.ReadString();
            break;
          }
          case 256: {
            ReturnMetadata = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  internal sealed partial class QueryWorkshopItemsResponse : pb::IMessage<QueryWorkshopItemsResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<QueryWorkshopItemsResponse> _parser = new pb::MessageParser<QueryWorkshopItemsResponse>(() => new QueryWorkshopItemsResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<QueryWorkshopItemsResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TEKSteamClient.CM.Messages.Bodies.QueryWorkshopItemsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QueryWorkshopItemsResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QueryWorkshopItemsResponse(QueryWorkshopItemsResponse other) : this() {
      total_ = other.total_;
      items_ = other.items_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QueryWorkshopItemsResponse Clone() {
      return new QueryWorkshopItemsResponse(this);
    }

    /// <summary>Field number for the "total" field.</summary>
    public const int TotalFieldNumber = 1;
    private uint total_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Total {
      get { return total_; }
      set {
        total_ = value;
      }
    }

    /// <summary>Field number for the "items" field.</summary>
    public const int ItemsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::TEKSteamClient.CM.Messages.Bodies.QueryWorkshopItemsResponse.Types.Item> _repeated_items_codec
        = pb::FieldCodec.ForMessage(18, global::TEKSteamClient.CM.Messages.Bodies.QueryWorkshopItemsResponse.Types.Item.Parser);
    private readonly pbc::RepeatedField<global::TEKSteamClient.CM.Messages.Bodies.QueryWorkshopItemsResponse.Types.Item> items_ = new pbc::RepeatedField<global::TEKSteamClient.CM.Messages.Bodies.QueryWorkshopItemsResponse.Types.Item>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::TEKSteamClient.CM.Messages.Bodies.QueryWorkshopItemsResponse.Types.Item> Items {
      get { return items_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as QueryWorkshopItemsResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(QueryWorkshopItemsResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Total != other.Total) return false;
      if(!items_.Equals(other.items_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Total != 0) hash ^= Total.GetHashCode();
      hash ^= items_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Total != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Total);
      }
      items_.WriteTo(output, _repeated_items_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Total != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Total);
      }
      items_.WriteTo(ref output, _repeated_items_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Total != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Total);
      }
      size += items_.CalculateSize(_repeated_items_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(QueryWorkshopItemsResponse other) {
      if (other == null) {
        return;
      }
      if (other.Total != 0) {
        Total = other.Total;
      }
      items_.Add(other.items_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Total = input.ReadUInt32();
            break;
          }
          case 18: {
            items_.AddEntriesFrom(input, _repeated_items_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Total = input.ReadUInt32();
            break;
          }
          case 18: {
            items_.AddEntriesFrom(ref input, _repeated_items_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the QueryWorkshopItemsResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      internal sealed partial class Item : pb::IMessage<Item>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Item> _parser = new pb::MessageParser<Item>(() => new Item());
        private pb::UnknownFieldSet _unknownFields;
        private int _hasBits0;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Item> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::TEKSteamClient.CM.Messages.Bodies.QueryWorkshopItemsResponse.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Item() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Item(Item other) : this() {
          _hasBits0 = other._hasBits0;
          result_ = other.result_;
          id_ = other.id_;
          previewUrl_ = other.previewUrl_;
          manifestId_ = other.manifestId_;
          name_ = other.name_;
          lastUpdated_ = other.lastUpdated_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Item Clone() {
          return new Item(this);
        }

        /// <summary>Field number for the "result" field.</summary>
        public const int ResultFieldNumber = 1;
        private readonly static int ResultDefaultValue = 0;

        private int result_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int Result {
          get { if ((_hasBits0 & 1) != 0) { return result_; } else { return ResultDefaultValue; } }
          set {
            _hasBits0 |= 1;
            result_ = value;
          }
        }
        /// <summary>Gets whether the "result" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasResult {
          get { return (_hasBits0 & 1) != 0; }
        }
        /// <summary>Clears the value of the "result" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearResult() {
          _hasBits0 &= ~1;
        }

        /// <summary>Field number for the "id" field.</summary>
        public const int IdFieldNumber = 2;
        private readonly static ulong IdDefaultValue = 0UL;

        private ulong id_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ulong Id {
          get { if ((_hasBits0 & 2) != 0) { return id_; } else { return IdDefaultValue; } }
          set {
            _hasBits0 |= 2;
            id_ = value;
          }
        }
        /// <summary>Gets whether the "id" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasId {
          get { return (_hasBits0 & 2) != 0; }
        }
        /// <summary>Clears the value of the "id" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearId() {
          _hasBits0 &= ~2;
        }

        /// <summary>Field number for the "preview_url" field.</summary>
        public const int PreviewUrlFieldNumber = 11;
        private readonly static string PreviewUrlDefaultValue = "";

        private string previewUrl_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string PreviewUrl {
          get { return previewUrl_ ?? PreviewUrlDefaultValue; }
          set {
            previewUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }
        /// <summary>Gets whether the "preview_url" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasPreviewUrl {
          get { return previewUrl_ != null; }
        }
        /// <summary>Clears the value of the "preview_url" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearPreviewUrl() {
          previewUrl_ = null;
        }

        /// <summary>Field number for the "manifest_id" field.</summary>
        public const int ManifestIdFieldNumber = 14;
        private readonly static ulong ManifestIdDefaultValue = 0UL;

        private ulong manifestId_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ulong ManifestId {
          get { if ((_hasBits0 & 4) != 0) { return manifestId_; } else { return ManifestIdDefaultValue; } }
          set {
            _hasBits0 |= 4;
            manifestId_ = value;
          }
        }
        /// <summary>Gets whether the "manifest_id" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasManifestId {
          get { return (_hasBits0 & 4) != 0; }
        }
        /// <summary>Clears the value of the "manifest_id" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearManifestId() {
          _hasBits0 &= ~4;
        }

        /// <summary>Field number for the "name" field.</summary>
        public const int NameFieldNumber = 16;
        private readonly static string NameDefaultValue = "";

        private string name_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Name {
          get { return name_ ?? NameDefaultValue; }
          set {
            name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }
        /// <summary>Gets whether the "name" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasName {
          get { return name_ != null; }
        }
        /// <summary>Clears the value of the "name" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearName() {
          name_ = null;
        }

        /// <summary>Field number for the "last_updated" field.</summary>
        public const int LastUpdatedFieldNumber = 20;
        private readonly static long LastUpdatedDefaultValue = 0L;

        private long lastUpdated_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public long LastUpdated {
          get { if ((_hasBits0 & 8) != 0) { return lastUpdated_; } else { return LastUpdatedDefaultValue; } }
          set {
            _hasBits0 |= 8;
            lastUpdated_ = value;
          }
        }
        /// <summary>Gets whether the "last_updated" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasLastUpdated {
          get { return (_hasBits0 & 8) != 0; }
        }
        /// <summary>Clears the value of the "last_updated" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearLastUpdated() {
          _hasBits0 &= ~8;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as Item);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Item other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Result != other.Result) return false;
          if (Id != other.Id) return false;
          if (PreviewUrl != other.PreviewUrl) return false;
          if (ManifestId != other.ManifestId) return false;
          if (Name != other.Name) return false;
          if (LastUpdated != other.LastUpdated) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (HasResult) hash ^= Result.GetHashCode();
          if (HasId) hash ^= Id.GetHashCode();
          if (HasPreviewUrl) hash ^= PreviewUrl.GetHashCode();
          if (HasManifestId) hash ^= ManifestId.GetHashCode();
          if (HasName) hash ^= Name.GetHashCode();
          if (HasLastUpdated) hash ^= LastUpdated.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (HasResult) {
            output.WriteRawTag(8);
            output.WriteInt32(Result);
          }
          if (HasId) {
            output.WriteRawTag(16);
            output.WriteUInt64(Id);
          }
          if (HasPreviewUrl) {
            output.WriteRawTag(90);
            output.WriteString(PreviewUrl);
          }
          if (HasManifestId) {
            output.WriteRawTag(113);
            output.WriteFixed64(ManifestId);
          }
          if (HasName) {
            output.WriteRawTag(130, 1);
            output.WriteString(Name);
          }
          if (HasLastUpdated) {
            output.WriteRawTag(160, 1);
            output.WriteInt64(LastUpdated);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (HasResult) {
            output.WriteRawTag(8);
            output.WriteInt32(Result);
          }
          if (HasId) {
            output.WriteRawTag(16);
            output.WriteUInt64(Id);
          }
          if (HasPreviewUrl) {
            output.WriteRawTag(90);
            output.WriteString(PreviewUrl);
          }
          if (HasManifestId) {
            output.WriteRawTag(113);
            output.WriteFixed64(ManifestId);
          }
          if (HasName) {
            output.WriteRawTag(130, 1);
            output.WriteString(Name);
          }
          if (HasLastUpdated) {
            output.WriteRawTag(160, 1);
            output.WriteInt64(LastUpdated);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (HasResult) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(Result);
          }
          if (HasId) {
            size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Id);
          }
          if (HasPreviewUrl) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(PreviewUrl);
          }
          if (HasManifestId) {
            size += 1 + 8;
          }
          if (HasName) {
            size += 2 + pb::CodedOutputStream.ComputeStringSize(Name);
          }
          if (HasLastUpdated) {
            size += 2 + pb::CodedOutputStream.ComputeInt64Size(LastUpdated);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Item other) {
          if (other == null) {
            return;
          }
          if (other.HasResult) {
            Result = other.Result;
          }
          if (other.HasId) {
            Id = other.Id;
          }
          if (other.HasPreviewUrl) {
            PreviewUrl = other.PreviewUrl;
          }
          if (other.HasManifestId) {
            ManifestId = other.ManifestId;
          }
          if (other.HasName) {
            Name = other.Name;
          }
          if (other.HasLastUpdated) {
            LastUpdated = other.LastUpdated;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                Result = input.ReadInt32();
                break;
              }
              case 16: {
                Id = input.ReadUInt64();
                break;
              }
              case 90: {
                PreviewUrl = input.ReadString();
                break;
              }
              case 113: {
                ManifestId = input.ReadFixed64();
                break;
              }
              case 130: {
                Name = input.ReadString();
                break;
              }
              case 160: {
                LastUpdated = input.ReadInt64();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                Result = input.ReadInt32();
                break;
              }
              case 16: {
                Id = input.ReadUInt64();
                break;
              }
              case 90: {
                PreviewUrl = input.ReadString();
                break;
              }
              case 113: {
                ManifestId = input.ReadFixed64();
                break;
              }
              case 130: {
                Name = input.ReadString();
                break;
              }
              case 160: {
                LastUpdated = input.ReadInt64();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
