// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: cm/messages/bodies/workshop_item_details.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace TEKSteamClient.CM.Messages.Bodies {

  /// <summary>Holder for reflection information generated from cm/messages/bodies/workshop_item_details.proto</summary>
  internal static partial class WorkshopItemDetailsReflection {

    #region Descriptor
    /// <summary>File descriptor for cm/messages/bodies/workshop_item_details.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WorkshopItemDetailsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci5jbS9tZXNzYWdlcy9ib2RpZXMvd29ya3Nob3BfaXRlbV9kZXRhaWxzLnBy",
            "b3RvEiF0ZWtzdGVhbWNsaWVudC5jbS5tZXNzYWdlcy5ib2RpZXMiigEKE1dv",
            "cmtzaG9wSXRlbURldGFpbHMSCwoDaWRzGAEgAygGEh0KEGluY2x1ZGVfY2hp",
            "bGRyZW4YBCABKAhIAIgBARIdChBpbmNsdWRlX21ldGFkYXRhGAsgASgISAGI",
            "AQFCEwoRX2luY2x1ZGVfY2hpbGRyZW5CEwoRX2luY2x1ZGVfbWV0YWRhdGEi",
            "4wMKG1dvcmtzaG9wSXRlbURldGFpbHNSZXNwb25zZRJSCgVpdGVtcxgBIAMo",
            "CzJDLnRla3N0ZWFtY2xpZW50LmNtLm1lc3NhZ2VzLmJvZGllcy5Xb3Jrc2hv",
            "cEl0ZW1EZXRhaWxzUmVzcG9uc2UuSXRlbRoXCglJdGVtQ2hpbGQSCgoCaWQY",
            "ASABKAQa1gIKBEl0ZW0SEwoGcmVzdWx0GAEgASgFSACIAQESDwoCaWQYAiAB",
            "KARIAYgBARITCgZhcHBfaWQYBSABKA1IAogBARIYCgtwcmV2aWV3X3VybBgL",
            "IAEoCUgDiAEBEhgKC21hbmlmZXN0X2lkGA4gASgGSASIAQESEQoEbmFtZRgQ",
            "IAEoCUgFiAEBEhkKDGxhc3RfdXBkYXRlZBgUIAEoA0gGiAEBEloKCGNoaWxk",
            "cmVuGDUgAygLMkgudGVrc3RlYW1jbGllbnQuY20ubWVzc2FnZXMuYm9kaWVz",
            "LldvcmtzaG9wSXRlbURldGFpbHNSZXNwb25zZS5JdGVtQ2hpbGRCCQoHX3Jl",
            "c3VsdEIFCgNfaWRCCQoHX2FwcF9pZEIOCgxfcHJldmlld191cmxCDgoMX21h",
            "bmlmZXN0X2lkQgcKBV9uYW1lQg8KDV9sYXN0X3VwZGF0ZWRCJKoCIVRFS1N0",
            "ZWFtQ2xpZW50LkNNLk1lc3NhZ2VzLkJvZGllc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::TEKSteamClient.CM.Messages.Bodies.WorkshopItemDetails), global::TEKSteamClient.CM.Messages.Bodies.WorkshopItemDetails.Parser, new[]{ "Ids", "IncludeChildren", "IncludeMetadata" }, new[]{ "IncludeChildren", "IncludeMetadata" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::TEKSteamClient.CM.Messages.Bodies.WorkshopItemDetailsResponse), global::TEKSteamClient.CM.Messages.Bodies.WorkshopItemDetailsResponse.Parser, new[]{ "Items" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::TEKSteamClient.CM.Messages.Bodies.WorkshopItemDetailsResponse.Types.ItemChild), global::TEKSteamClient.CM.Messages.Bodies.WorkshopItemDetailsResponse.Types.ItemChild.Parser, new[]{ "Id" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::TEKSteamClient.CM.Messages.Bodies.WorkshopItemDetailsResponse.Types.Item), global::TEKSteamClient.CM.Messages.Bodies.WorkshopItemDetailsResponse.Types.Item.Parser, new[]{ "Result", "Id", "AppId", "PreviewUrl", "ManifestId", "Name", "LastUpdated", "Children" }, new[]{ "Result", "Id", "AppId", "PreviewUrl", "ManifestId", "Name", "LastUpdated" }, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  internal sealed partial class WorkshopItemDetails : pb::IMessage<WorkshopItemDetails>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WorkshopItemDetails> _parser = new pb::MessageParser<WorkshopItemDetails>(() => new WorkshopItemDetails());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WorkshopItemDetails> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TEKSteamClient.CM.Messages.Bodies.WorkshopItemDetailsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorkshopItemDetails() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorkshopItemDetails(WorkshopItemDetails other) : this() {
      _hasBits0 = other._hasBits0;
      ids_ = other.ids_.Clone();
      includeChildren_ = other.includeChildren_;
      includeMetadata_ = other.includeMetadata_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorkshopItemDetails Clone() {
      return new WorkshopItemDetails(this);
    }

    /// <summary>Field number for the "ids" field.</summary>
    public const int IdsFieldNumber = 1;
    private static readonly pb::FieldCodec<ulong> _repeated_ids_codec
        = pb::FieldCodec.ForFixed64(10);
    private readonly pbc::RepeatedField<ulong> ids_ = new pbc::RepeatedField<ulong>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<ulong> Ids {
      get { return ids_; }
    }

    /// <summary>Field number for the "include_children" field.</summary>
    public const int IncludeChildrenFieldNumber = 4;
    private readonly static bool IncludeChildrenDefaultValue = false;

    private bool includeChildren_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IncludeChildren {
      get { if ((_hasBits0 & 1) != 0) { return includeChildren_; } else { return IncludeChildrenDefaultValue; } }
      set {
        _hasBits0 |= 1;
        includeChildren_ = value;
      }
    }
    /// <summary>Gets whether the "include_children" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasIncludeChildren {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "include_children" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearIncludeChildren() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "include_metadata" field.</summary>
    public const int IncludeMetadataFieldNumber = 11;
    private readonly static bool IncludeMetadataDefaultValue = false;

    private bool includeMetadata_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IncludeMetadata {
      get { if ((_hasBits0 & 2) != 0) { return includeMetadata_; } else { return IncludeMetadataDefaultValue; } }
      set {
        _hasBits0 |= 2;
        includeMetadata_ = value;
      }
    }
    /// <summary>Gets whether the "include_metadata" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasIncludeMetadata {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "include_metadata" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearIncludeMetadata() {
      _hasBits0 &= ~2;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WorkshopItemDetails);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WorkshopItemDetails other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!ids_.Equals(other.ids_)) return false;
      if (IncludeChildren != other.IncludeChildren) return false;
      if (IncludeMetadata != other.IncludeMetadata) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= ids_.GetHashCode();
      if (HasIncludeChildren) hash ^= IncludeChildren.GetHashCode();
      if (HasIncludeMetadata) hash ^= IncludeMetadata.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      ids_.WriteTo(output, _repeated_ids_codec);
      if (HasIncludeChildren) {
        output.WriteRawTag(32);
        output.WriteBool(IncludeChildren);
      }
      if (HasIncludeMetadata) {
        output.WriteRawTag(88);
        output.WriteBool(IncludeMetadata);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      ids_.WriteTo(ref output, _repeated_ids_codec);
      if (HasIncludeChildren) {
        output.WriteRawTag(32);
        output.WriteBool(IncludeChildren);
      }
      if (HasIncludeMetadata) {
        output.WriteRawTag(88);
        output.WriteBool(IncludeMetadata);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += ids_.CalculateSize(_repeated_ids_codec);
      if (HasIncludeChildren) {
        size += 1 + 1;
      }
      if (HasIncludeMetadata) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WorkshopItemDetails other) {
      if (other == null) {
        return;
      }
      ids_.Add(other.ids_);
      if (other.HasIncludeChildren) {
        IncludeChildren = other.IncludeChildren;
      }
      if (other.HasIncludeMetadata) {
        IncludeMetadata = other.IncludeMetadata;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10:
          case 9: {
            ids_.AddEntriesFrom(input, _repeated_ids_codec);
            break;
          }
          case 32: {
            IncludeChildren = input.ReadBool();
            break;
          }
          case 88: {
            IncludeMetadata = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10:
          case 9: {
            ids_.AddEntriesFrom(ref input, _repeated_ids_codec);
            break;
          }
          case 32: {
            IncludeChildren = input.ReadBool();
            break;
          }
          case 88: {
            IncludeMetadata = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  internal sealed partial class WorkshopItemDetailsResponse : pb::IMessage<WorkshopItemDetailsResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WorkshopItemDetailsResponse> _parser = new pb::MessageParser<WorkshopItemDetailsResponse>(() => new WorkshopItemDetailsResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WorkshopItemDetailsResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TEKSteamClient.CM.Messages.Bodies.WorkshopItemDetailsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorkshopItemDetailsResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorkshopItemDetailsResponse(WorkshopItemDetailsResponse other) : this() {
      items_ = other.items_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorkshopItemDetailsResponse Clone() {
      return new WorkshopItemDetailsResponse(this);
    }

    /// <summary>Field number for the "items" field.</summary>
    public const int ItemsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::TEKSteamClient.CM.Messages.Bodies.WorkshopItemDetailsResponse.Types.Item> _repeated_items_codec
        = pb::FieldCodec.ForMessage(10, global::TEKSteamClient.CM.Messages.Bodies.WorkshopItemDetailsResponse.Types.Item.Parser);
    private readonly pbc::RepeatedField<global::TEKSteamClient.CM.Messages.Bodies.WorkshopItemDetailsResponse.Types.Item> items_ = new pbc::RepeatedField<global::TEKSteamClient.CM.Messages.Bodies.WorkshopItemDetailsResponse.Types.Item>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::TEKSteamClient.CM.Messages.Bodies.WorkshopItemDetailsResponse.Types.Item> Items {
      get { return items_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WorkshopItemDetailsResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WorkshopItemDetailsResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!items_.Equals(other.items_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= items_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      items_.WriteTo(output, _repeated_items_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      items_.WriteTo(ref output, _repeated_items_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += items_.CalculateSize(_repeated_items_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WorkshopItemDetailsResponse other) {
      if (other == null) {
        return;
      }
      items_.Add(other.items_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            items_.AddEntriesFrom(input, _repeated_items_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            items_.AddEntriesFrom(ref input, _repeated_items_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the WorkshopItemDetailsResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      internal sealed partial class ItemChild : pb::IMessage<ItemChild>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<ItemChild> _parser = new pb::MessageParser<ItemChild>(() => new ItemChild());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<ItemChild> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::TEKSteamClient.CM.Messages.Bodies.WorkshopItemDetailsResponse.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ItemChild() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ItemChild(ItemChild other) : this() {
          id_ = other.id_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ItemChild Clone() {
          return new ItemChild(this);
        }

        /// <summary>Field number for the "id" field.</summary>
        public const int IdFieldNumber = 1;
        private ulong id_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ulong Id {
          get { return id_; }
          set {
            id_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as ItemChild);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(ItemChild other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Id != other.Id) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (Id != 0UL) hash ^= Id.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (Id != 0UL) {
            output.WriteRawTag(8);
            output.WriteUInt64(Id);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (Id != 0UL) {
            output.WriteRawTag(8);
            output.WriteUInt64(Id);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (Id != 0UL) {
            size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Id);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(ItemChild other) {
          if (other == null) {
            return;
          }
          if (other.Id != 0UL) {
            Id = other.Id;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                Id = input.ReadUInt64();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                Id = input.ReadUInt64();
                break;
              }
            }
          }
        }
        #endif

      }

      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      internal sealed partial class Item : pb::IMessage<Item>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Item> _parser = new pb::MessageParser<Item>(() => new Item());
        private pb::UnknownFieldSet _unknownFields;
        private int _hasBits0;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Item> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::TEKSteamClient.CM.Messages.Bodies.WorkshopItemDetailsResponse.Descriptor.NestedTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Item() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Item(Item other) : this() {
          _hasBits0 = other._hasBits0;
          result_ = other.result_;
          id_ = other.id_;
          appId_ = other.appId_;
          previewUrl_ = other.previewUrl_;
          manifestId_ = other.manifestId_;
          name_ = other.name_;
          lastUpdated_ = other.lastUpdated_;
          children_ = other.children_.Clone();
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Item Clone() {
          return new Item(this);
        }

        /// <summary>Field number for the "result" field.</summary>
        public const int ResultFieldNumber = 1;
        private readonly static int ResultDefaultValue = 0;

        private int result_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int Result {
          get { if ((_hasBits0 & 1) != 0) { return result_; } else { return ResultDefaultValue; } }
          set {
            _hasBits0 |= 1;
            result_ = value;
          }
        }
        /// <summary>Gets whether the "result" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasResult {
          get { return (_hasBits0 & 1) != 0; }
        }
        /// <summary>Clears the value of the "result" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearResult() {
          _hasBits0 &= ~1;
        }

        /// <summary>Field number for the "id" field.</summary>
        public const int IdFieldNumber = 2;
        private readonly static ulong IdDefaultValue = 0UL;

        private ulong id_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ulong Id {
          get { if ((_hasBits0 & 2) != 0) { return id_; } else { return IdDefaultValue; } }
          set {
            _hasBits0 |= 2;
            id_ = value;
          }
        }
        /// <summary>Gets whether the "id" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasId {
          get { return (_hasBits0 & 2) != 0; }
        }
        /// <summary>Clears the value of the "id" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearId() {
          _hasBits0 &= ~2;
        }

        /// <summary>Field number for the "app_id" field.</summary>
        public const int AppIdFieldNumber = 5;
        private readonly static uint AppIdDefaultValue = 0;

        private uint appId_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint AppId {
          get { if ((_hasBits0 & 4) != 0) { return appId_; } else { return AppIdDefaultValue; } }
          set {
            _hasBits0 |= 4;
            appId_ = value;
          }
        }
        /// <summary>Gets whether the "app_id" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasAppId {
          get { return (_hasBits0 & 4) != 0; }
        }
        /// <summary>Clears the value of the "app_id" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearAppId() {
          _hasBits0 &= ~4;
        }

        /// <summary>Field number for the "preview_url" field.</summary>
        public const int PreviewUrlFieldNumber = 11;
        private readonly static string PreviewUrlDefaultValue = "";

        private string previewUrl_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string PreviewUrl {
          get { return previewUrl_ ?? PreviewUrlDefaultValue; }
          set {
            previewUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }
        /// <summary>Gets whether the "preview_url" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasPreviewUrl {
          get { return previewUrl_ != null; }
        }
        /// <summary>Clears the value of the "preview_url" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearPreviewUrl() {
          previewUrl_ = null;
        }

        /// <summary>Field number for the "manifest_id" field.</summary>
        public const int ManifestIdFieldNumber = 14;
        private readonly static ulong ManifestIdDefaultValue = 0UL;

        private ulong manifestId_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ulong ManifestId {
          get { if ((_hasBits0 & 8) != 0) { return manifestId_; } else { return ManifestIdDefaultValue; } }
          set {
            _hasBits0 |= 8;
            manifestId_ = value;
          }
        }
        /// <summary>Gets whether the "manifest_id" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasManifestId {
          get { return (_hasBits0 & 8) != 0; }
        }
        /// <summary>Clears the value of the "manifest_id" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearManifestId() {
          _hasBits0 &= ~8;
        }

        /// <summary>Field number for the "name" field.</summary>
        public const int NameFieldNumber = 16;
        private readonly static string NameDefaultValue = "";

        private string name_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Name {
          get { return name_ ?? NameDefaultValue; }
          set {
            name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }
        /// <summary>Gets whether the "name" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasName {
          get { return name_ != null; }
        }
        /// <summary>Clears the value of the "name" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearName() {
          name_ = null;
        }

        /// <summary>Field number for the "last_updated" field.</summary>
        public const int LastUpdatedFieldNumber = 20;
        private readonly static long LastUpdatedDefaultValue = 0L;

        private long lastUpdated_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public long LastUpdated {
          get { if ((_hasBits0 & 16) != 0) { return lastUpdated_; } else { return LastUpdatedDefaultValue; } }
          set {
            _hasBits0 |= 16;
            lastUpdated_ = value;
          }
        }
        /// <summary>Gets whether the "last_updated" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasLastUpdated {
          get { return (_hasBits0 & 16) != 0; }
        }
        /// <summary>Clears the value of the "last_updated" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearLastUpdated() {
          _hasBits0 &= ~16;
        }

        /// <summary>Field number for the "children" field.</summary>
        public const int ChildrenFieldNumber = 53;
        private static readonly pb::FieldCodec<global::TEKSteamClient.CM.Messages.Bodies.WorkshopItemDetailsResponse.Types.ItemChild> _repeated_children_codec
            = pb::FieldCodec.ForMessage(426, global::TEKSteamClient.CM.Messages.Bodies.WorkshopItemDetailsResponse.Types.ItemChild.Parser);
        private readonly pbc::RepeatedField<global::TEKSteamClient.CM.Messages.Bodies.WorkshopItemDetailsResponse.Types.ItemChild> children_ = new pbc::RepeatedField<global::TEKSteamClient.CM.Messages.Bodies.WorkshopItemDetailsResponse.Types.ItemChild>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::RepeatedField<global::TEKSteamClient.CM.Messages.Bodies.WorkshopItemDetailsResponse.Types.ItemChild> Children {
          get { return children_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as Item);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Item other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Result != other.Result) return false;
          if (Id != other.Id) return false;
          if (AppId != other.AppId) return false;
          if (PreviewUrl != other.PreviewUrl) return false;
          if (ManifestId != other.ManifestId) return false;
          if (Name != other.Name) return false;
          if (LastUpdated != other.LastUpdated) return false;
          if(!children_.Equals(other.children_)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (HasResult) hash ^= Result.GetHashCode();
          if (HasId) hash ^= Id.GetHashCode();
          if (HasAppId) hash ^= AppId.GetHashCode();
          if (HasPreviewUrl) hash ^= PreviewUrl.GetHashCode();
          if (HasManifestId) hash ^= ManifestId.GetHashCode();
          if (HasName) hash ^= Name.GetHashCode();
          if (HasLastUpdated) hash ^= LastUpdated.GetHashCode();
          hash ^= children_.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (HasResult) {
            output.WriteRawTag(8);
            output.WriteInt32(Result);
          }
          if (HasId) {
            output.WriteRawTag(16);
            output.WriteUInt64(Id);
          }
          if (HasAppId) {
            output.WriteRawTag(40);
            output.WriteUInt32(AppId);
          }
          if (HasPreviewUrl) {
            output.WriteRawTag(90);
            output.WriteString(PreviewUrl);
          }
          if (HasManifestId) {
            output.WriteRawTag(113);
            output.WriteFixed64(ManifestId);
          }
          if (HasName) {
            output.WriteRawTag(130, 1);
            output.WriteString(Name);
          }
          if (HasLastUpdated) {
            output.WriteRawTag(160, 1);
            output.WriteInt64(LastUpdated);
          }
          children_.WriteTo(output, _repeated_children_codec);
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (HasResult) {
            output.WriteRawTag(8);
            output.WriteInt32(Result);
          }
          if (HasId) {
            output.WriteRawTag(16);
            output.WriteUInt64(Id);
          }
          if (HasAppId) {
            output.WriteRawTag(40);
            output.WriteUInt32(AppId);
          }
          if (HasPreviewUrl) {
            output.WriteRawTag(90);
            output.WriteString(PreviewUrl);
          }
          if (HasManifestId) {
            output.WriteRawTag(113);
            output.WriteFixed64(ManifestId);
          }
          if (HasName) {
            output.WriteRawTag(130, 1);
            output.WriteString(Name);
          }
          if (HasLastUpdated) {
            output.WriteRawTag(160, 1);
            output.WriteInt64(LastUpdated);
          }
          children_.WriteTo(ref output, _repeated_children_codec);
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (HasResult) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(Result);
          }
          if (HasId) {
            size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Id);
          }
          if (HasAppId) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(AppId);
          }
          if (HasPreviewUrl) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(PreviewUrl);
          }
          if (HasManifestId) {
            size += 1 + 8;
          }
          if (HasName) {
            size += 2 + pb::CodedOutputStream.ComputeStringSize(Name);
          }
          if (HasLastUpdated) {
            size += 2 + pb::CodedOutputStream.ComputeInt64Size(LastUpdated);
          }
          size += children_.CalculateSize(_repeated_children_codec);
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Item other) {
          if (other == null) {
            return;
          }
          if (other.HasResult) {
            Result = other.Result;
          }
          if (other.HasId) {
            Id = other.Id;
          }
          if (other.HasAppId) {
            AppId = other.AppId;
          }
          if (other.HasPreviewUrl) {
            PreviewUrl = other.PreviewUrl;
          }
          if (other.HasManifestId) {
            ManifestId = other.ManifestId;
          }
          if (other.HasName) {
            Name = other.Name;
          }
          if (other.HasLastUpdated) {
            LastUpdated = other.LastUpdated;
          }
          children_.Add(other.children_);
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                Result = input.ReadInt32();
                break;
              }
              case 16: {
                Id = input.ReadUInt64();
                break;
              }
              case 40: {
                AppId = input.ReadUInt32();
                break;
              }
              case 90: {
                PreviewUrl = input.ReadString();
                break;
              }
              case 113: {
                ManifestId = input.ReadFixed64();
                break;
              }
              case 130: {
                Name = input.ReadString();
                break;
              }
              case 160: {
                LastUpdated = input.ReadInt64();
                break;
              }
              case 426: {
                children_.AddEntriesFrom(input, _repeated_children_codec);
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                Result = input.ReadInt32();
                break;
              }
              case 16: {
                Id = input.ReadUInt64();
                break;
              }
              case 40: {
                AppId = input.ReadUInt32();
                break;
              }
              case 90: {
                PreviewUrl = input.ReadString();
                break;
              }
              case 113: {
                ManifestId = input.ReadFixed64();
                break;
              }
              case 130: {
                Name = input.ReadString();
                break;
              }
              case 160: {
                LastUpdated = input.ReadInt64();
                break;
              }
              case 426: {
                children_.AddEntriesFrom(ref input, _repeated_children_codec);
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
